### PR TITLE
Add compile_time false to suppress warning for issue #48

### PR DESCRIPTION
**Pull request by davidjh**

### CODE REVIEW

**Comment by joekiller** [comment]
Thanks!

**Comment by davidjh** [comment]
Hi Joe, can you share to Chef Supermarket when you get a chance?

**Comment by joekiller** [comment]
Should be there now.

**Comment by bmhatfield** [comment]
Hi Guys,

This change breaks s3_file for me (on new nodes). The old behavior was `compile_time true` - I get the obvious exception (`cannot load such file -- rest-client`) if it's `false`. Changing this back to `true` works great. Chef-client 12.4.3 (due to bugs in 12.5~).

**Comment by joekiller** [comment]
okay try 2.6.6

**Pull request merged**
