### PR TITLE
Handle exceptions which do not respond to .response

### PR DESCRIPTION
**Pull request by dldinternet**
The rescue code assumes that the exception caught will respond to .response for the Chef::Log of the exception.
Certain exceptions like Errno::ENOENT etc. will not work with this exception handling logic.
Use at your own discretion or implement a better exception handler perhaps.

### CODE REVIEW

**Comment by joekiller** [comment]
This looks pretty good. Care to rebase so I can merge it in?

**Comment by dldinternet** [comment]
I have rebased the PR to be up to date with development since this PR was created ... 11 months ago! LOL

**Comment by joekiller** [comment]
Thanks! :)

**Comment by joekiller** [comment]
Feel like it's ready now? Just noticed an additional commit.

**Comment by dldinternet** [comment]
Yep all done. Sorry, could not resist the last optimization

**Comment by joekiller** [comment]
Thanks!

**Pull request merged**
