### PR TITLE
Detect a dot and, if present, use "path style" S3 URL

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by joekiller** [comment]
This should be live in v2.6.4.

Thanks for the contribution!

**Comment by workeitel** [comment]
There is the same problem with `_` and uppercase characters which are not allowed in virtual domain style addressing but in path style addressing. Any chance to get this included into the condition as well?

**Comment by joekiller** [comment]
I wonder if we should just always put the bucket name on the target.

**Comment by workeitel** [comment]
I think a good reference for decide path style vs virtual domain style is the official aws ruby sdk https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/plugins/s3_bucket_dns.rb#L76

Looking at the documentation http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html the advantage is (unless the regions is included in path style addressing) that it needs to always asks in us-east-1 for the right region and then queries this region for the object. Using virtual domain style addressing solves this because the DNS name is a CNAME to the right region.

In addition I could imagine that people using a proxy for filtering traffic for security. This will be difficult with path style addressing because the bucket is encoded in the path - in virtual domain style addressing it's easy to filter based on the hostname.

Another suggestion would be to leave it to the caller of the resource to provide the url and not do the detection in the s3_file resource - but this would require a breaking API change of the s3_file resource.

**Pull request merged**
